### ISSUE TITLE
License

### ISSUE THREAD

**Issue by virustotalop** [notaudrey/adblocker#1]
I was wondering what the license for the specific project is? There are a variety of license options out there for you to choose from, I was wondering in case anyone comes along and wants to use the project but wants to know their rights. Also for the ServerListPing class the original seems to be from zh32 and is located here: https://gist.github.com/zh32/7190955.

**Comment by notaudrey** [comment]
License information has been added, as well as credit to @zh32 for the `ServerListPing` class.

**Comment by zh32** [comment]
https://gist.github.com/zh32/7190955#gistcomment-1901075
